back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /back

ys:
    resource: "@YSBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

